server:
  port: 8088
spring:
  application:
    name: xdu-microservice-dtssyncclear
logging:
  level:
    root: INFO
    com.huawei.xdu: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.252.211.16:10001/eureka/
  instance:
    preferIpAddress: true